[package]
name = "slurmactiond"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4" # HTTP / web framework
awc = { version = "3", features = ["openssl"] } # HTTP client implementation used by actix-web
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
shell-escape = "0.1"
toml = "0.5" # for config files
log = "0.4"
env_logger = "0.9"
derive_more = "0.99"
regex = "1"
