[slurm]
#sbatch = "/usr/bin/sbatch"
#sbatch_args = ["-A", "account"]

[action_runner]
tarball = "/home/cirunner/actions-runner-linux-x64-2.290.1.tar.gz"
#group = "slurm"
name_prefix = "slurmactiond"
base_labels = ["slurm"]
repository_url = "https://github.com/celerity/slurmactiond"
registration_token = "A1b2C3d4E5f6"

[[mappings]]
runner_labels = ["nvidia"]
sbatch_args = ["-p", "nv"]

[[mappings]]
runner_labels = ["intel"]
sbatch_args = ["-p", "intel"]

[http]
bind = "127.0.0.1:6020"
