[http]
bind = "127.0.0.1:8020"

[slurm]
#sbatch = "/usr/bin/sbatch"
sbatch_options = ["-t", "1:00:00"]
job_name = "action-runner"

[action_runner]
tarball = "/home/cirunner/actions-runner-linux-x64-2.290.1.tar.gz"
work_dir = "/home/cirunner/slurmactiond"

[action_runner.registration]
url = "https://github.com/celerity"
token = "A1b2C3d4E5f6"
name = "slurm"
labels = ["slurm", "dc-03"]

[partitions.gpu]
runner_labels = ["gpu", "db-app"]
sbatch_options = ["-p", "gpu"]

[partitions.intel]
runner_labels = ["gpu", "db-app", "intel"]
sbatch_options = ["-p", "intel"]
