[http]
bind = "127.0.0.1:8020"
secret = "as specified in the Webhook Configuration"

[github]
entity = "celerity/slurmactiond"
api_token = "ghp_5Hx6y27fF10fjF01jfJpQrtT915931520A"

[slurm]
#srun = "/usr/bin/srun"
srun_options = ["-t", "1:00:00"]
job_name = "action-runner"

[action_runner]
platform = "linux-x64"
work_dir = "/home/cirunner/slurmactiond"

[action_runner.registration]
name = "slurm"
labels = ["slurm", "dc-03"]

[targets.gpu]
runner_labels = ["gpu", "db-app"]
srun_options = ["-p", "gpu"]

[targets.intel]
runner_labels = ["gpu", "db-app", "intel"]
srun_options = ["-p", "intel"]
