[http]
bind = "127.0.0.1:8020"
secret = "as specified in the Webhook Configuration"

[github]
entity = "celerity/slurmactiond"
api_token = "ghp_5Hx6y27fF10fjF01jfJpQrtT915931520A"

[slurm]
#srun = "srun"
#squeue = "squeue"
srun_options = ["-t", "1:00:00"]
# srun_env = { DEFAULT_OPTION = "ALL" }
job_name = "actions"

[action_runner]
platform = "linux-x64"
work_dir = "/home/cirunner/slurmactiond"
# listen_timeout_s = 300

[action_runner.registration]
name = "slurm"
labels = ["slurm", "dc-03"]

[targets.gpu]
runner_labels = ["gpu", "db-app"]
srun_options = ["-p", "gpu"]
priority = 1 # lower value is higher priority in case multiple targets apply to one job

[targets.intel]
runner_labels = ["gpu", "db-app", "intel"]
srun_options = ["-p", "intel"]
priority = 2
# srun_env = { RUNNER_OPTION = "VALUE" }
